### ISSUE TITLE
Fails to bundle when there are identical modules

### ISSUE THREAD

**Issue by bakkot** [shapesecurity/bandolier#72]
If there are two modules in the graph with identical ASTs, bandolier will not build the graph. For example:

```sh
./bin/bandolier.sh a.js
```

```js
// a.js
import './b.js';
import './c.js';
```
```js
// b.js
console.log(0);
```
```js
// c.js
console.log(0);
```

results in
```
Exception in thread "main" com.shapesecurity.bandolier.es2017.loader.ModuleLoaderException: Module Loader Exception: module /bandolier/a.js cannot be loaded: Not all modules were scheduled: 2 / 3.
Unscheduled modules:

	at com.shapesecurity.bandolier.es2017.Bundler.bundleString(Bundler.java:115)
	at com.shapesecurity.bandolier.es2017.Bundler.bundle(Bundler.java:79)
	at com.shapesecurity.bandolier.es2017.Main.main(Main.java:48)
Caused by: java.lang.RuntimeException: Not all modules were scheduled: 2 / 3.
Unscheduled modules:

	at com.shapesecurity.bandolier.es2017.transformations.ImportExportConnector.combineModules(ImportExportConnector.java:463)
	at com.shapesecurity.bandolier.es2017.bundlers.PiercedModuleBundler.bundleEntrypoint(PiercedModuleBundler.java:47)
	at com.shapesecurity.bandolier.es2017.Bundler.bundleString(Bundler.java:113)
	... 2 more
```

**Comment by hewholived** [comment]
I'll be working on this.
